actions:
  1:
    action: restore
    description: restore elastic search files.
    options:
      repository: my_backup
      # Leaving name blank will result in the default 'curator-%Y%m%d%H%M%S'
      name: 
      indices:
      wait_for_completion: True
      max_wait: 3600
      wait_interval: 10
      extra_settings:
        index_settings:
          number_of_replicas: 0
    filters:
    - filtertype: state
      state: SUCCESS
      exclude:
      
